#:include animation.kv
#:include login.kv
#:include signup.kv
#:include home.kv
#:include profile.kv
#:include settings.kv

ScreenManager:
    MainScreen:
        name: "main"
    WelcomeScreen:
        name: "welcome"
    LoginScreen:
        name: "login"
    SignUpScreen:
        name: "signup"
    HomeScreen:
        name: "home"
    ProfileScreen:
        name: "profile"
    SettingsScreen:
        name: "settings"